### ISSUE TITLE
Out of date package on http://static.drupal-packagist.org

### ISSUE THREAD

**Issue by pbuyle** [drupal-composer/drupal-composer-project#2]
When using http://static.drupal-packagist.org/v0.2.0/ as repository, we noticed that when adding a dependency for Features using `"drupal/features": "7.2~"`, version 7.2.2 is downloaded while 7.2.3 has been released on January the 5th. If we use `"drupal/features": "7.2.3" `, then composer is unable to resolved the dependency.

Is http://static.drupal-packagist.org maintained and frequently updated ?

**Comment by mikkeschiren** [comment]
I am using http://drupal-packagist.webflo.io/ - it seems to be more up to date.

**Comment by pbuyle** [comment]
We did the same. But it uses a different approaches, it would be interesting to known which ones are maintained and where to report issue with them.

**Comment by kasperg** [comment]
Thanks for reporting this. You are right that http://drupal-packagist.webflo.io/ is the way to go currently.

[This fork](https://github.com/derhasi/drupal-composer-project) by @derhasi changes this change as well as other improvements e.g. better handling of Core. I have suggested that we [merge the two repos](https://github.com/derhasi/drupal-composer-project) and transfer ownership to the [drupal-composer organization](https://github.com/drupal-composer) to mark which one has community support.

**Comment by derhasi** [comment]
I merged https://github.com/drupal-composer/drupal-composer-project/pull/5, so this issue should be fixed with the new Drupal Packagist Server running on packagist.drupal-composer.org.

The Code for the packagist server is maintained within this "Drupal Composer" organisation.
* https://github.com/drupal-composer/drupal-parse-composer : Component for parsing project data from drupal.org
* https://github.com/drupal-composer/drupal-packagist : Application that runs on the server and uses drupal-parse-composer (is a fork of the [original packagist](https://github.com/composer/packagist))
