### ISSUE TITLE
delete the duplicate web/core/vendor in post-install.sh ?

### ISSUE THREAD

**Issue by yched** [drupal-composer/drupal-composer-project#23]
All dependencies, including core's, are downloaded by composer in the root /vendor, and this is the directory that is targetted by the web/autoloader.php that is effectively used by the drupal code.

So the web/core/vendor that is currently committed in the core repo is dead code, and just adds confusion (triggers duplicates when navigating the codebase in an IDE...)

**Comment by webflo** [comment]
:+1: Was not possible before beta10 because of https://www.drupal.org/node/2468499 and https://www.drupal.org/node/2458045.

**Comment by webflo** [comment]
I think its not that easy, because composer will detect these changes and make the installed packages as modified.

**Comment by yched** [comment]
Oh. Right. Bummer.

Could this be worked around with the [discard-changes: stash](https://getcomposer.org/doc/04-schema.md#config) option ?

**Comment by webflo** [comment]
Yes, we can do this. A other way around this issue is a subtree split without vendor, and there is a core issues where we discuss to remove vendor, and there was not much resistance against it during the Composer BOF in LA. So maybe we should push the core issue forward and use the stash options in the meantime. Core issues to move vendor: https://www.drupal.org/node/2380389

**Comment by yched** [comment]
Yep, agreed.

I wish I was there in that BoF in LA :-)

**Comment by webflo** [comment]
https://twitter.com/webflo/status/649339497663098880

**Comment by yched** [comment]
\o/

@webflo ++
