### ISSUE TITLE
phpunit/phpunit dependency improvemnt

### ISSUE THREAD

**Issue by urbantom** [drupal-composer/drupal-composer-project#242]
Could you improve phpunit/phpunit dev dependency from ~4.8 to ~4.8|~5.7?

Context: current phing/phing (3.0.x-dev) package requires sebastian/version ^2.0. On the other hand phpunit/phpunit 4.8.34 (complying the criteria ~4.8 defined in composer.json distributed with drupal-composer/drupal-project:8.x-dev project) requires phpunit/php-code-coverage: "~2.1". Next, phpunit/php-code-coverage 2.2.4 (complying the criteria ~2.1) requires sebastian/version ~1.0. And this is a show stopper in installing the latest phing/phing.

If you admit also phpunit/phpunit: "~5.7", then phpunit/phpunit 5.7.9 (complying the criteria ~5.7) will require phpunit/php-code-coverage: "^4.0.4". Next, phpunit/php-code-coverage 4.0.5 (complying the criteria ^4.0.4) will require sebastian/version: ~1.0|~2.0.

It should let build (but not crack) environment that provides drupal/core as well as phing/phing?

**Comment by webflo** [comment]
Lets ping some people from the PHPUnit Initiative and phing users.

@dawehner Are you aware of any issues with a newer phpunit version?
@pfrenssen I think you are using phing right? How do you do it?

Thanks!

**Comment by urbantom** [comment]
Thank you for the quick response and a social approach to find an optimal solution.

**Comment by pfrenssen** [comment]
Is this a recent development? I'll update my fork that integrates Phing with drupal-project and have a look.

**Comment by pfrenssen** [comment]
I'm not affected since I am using the latest stable Phing 2.16.0. The 3.x branch of Phing is currently in early pre-alpha development, and doesn't have a single release. I have no reasons right now to switch to Phing 3.x, but I'm very much interested in it once it stabilizes since the goal of this new version is to greatly modernize the code base.

I don't think it would be a good idea for drupal-project to declare compatibility with PHPUnit 5.7 just for the sake that a 3.x development branch of Phing exists. I think we should first check if PHPUnit 5.7 is fully compatible with Drupal. If the full core test suite passes using PHPUnit 5.7 then we can definitely start endorsing it.

**Comment by urbantom** [comment]
Thank you for the benevolent treatment of my request.
Thank you for hint of using  the latest stable Phing 2.16.0. I'll follow this path.

**Comment by urbantom** [comment]
Thank you for hint of using  the latest stable Phing 2.16.0. I'll follow this path.
