### ISSUE TITLE
Add Preserve Paths?

### ISSUE THREAD

**Issue by RobLoach** [drupal-composer/drupal-composer-project#298]
https://github.com/drupal-composer/preserve-paths

Think we should add this? May be helpful.

**Comment by webflo** [comment]
Whats the use case for the D8 branch? I think its best to store custom code and code managed by composer in different directories.

**Comment by thomascys** [comment]
I use drupal-composer/preserve-paths to store custom modules but would like to know more about your approach @webflo

**Comment by webflo** [comment]
You should be able to it with plain [Composer Installers](https://github.com/composer/installers#custom-install-paths). Make sure you add your custom stuff above the "type:drupal-module". Because composers uses the first one that matches.

Composer installers has the notion of "custom-theme" and "custom-module". You can use this type as well. https://github.com/composer/installers/blob/master/src/Composer/Installers/DrupalInstaller.php#L13

**Comment by webflo** [comment]
[::getInstallPath](https://github.com/composer/installers/blob/master/src/Composer/Installers/BaseInstaller.php#L36) is the method which determines the install path.

**Comment by thomascys** [comment]
That approach doesn't really seem practical if you're actually developing your custom modules.

**Comment by webflo** [comment]
Could you explain your workflow a little bit more? I get why its usefull in D7 setups with nested packages, but thats not the case in D8.

Thanks!

**Comment by thomascys** [comment]
I've did some testing without preserve-paths and didn't encounter any use cases where composer removes custom directories under themes or modules.
I assumed preserve-paths was still necessary to let composer know that it cannot remove files/directories under 'themes/custom' or 'modules/custom' on composer install or composer update.
My bad, i got that all wrong. Sorry for the confusion.

**Comment by webflo** [comment]
Np :)

@RobLoach Can we close the issue?

**Comment by RobLoach** [comment]
@webflo Of course! Thanks for the explanation :+1:

**Comment by OnkelTem** [comment]
Guys, `drupal-composer/preserve-paths` package makes problems here on Drupal 7, particularly trying to move (backup) `sites/default` directory which is a docker mount and can not be removed. I don't think we need it after all - it runs fine on Drupal 8, right? Let's remove it from drupal 7's version?

**Comment by RobLoach** [comment]
> runs fine on Drupal 8, right?

Intent was for Drupal 8. Don't think we absolutely need it in the base drupal-project project though.

**Comment by OnkelTem** [comment]
> Intent was for Drupal 8. Don't think we absolutely need it in the base drupal-project project though.

Hehe, I'm not sure that I get you right. Probably because of my bad phrasing.

I use **drupal-composer** for Drupal 7 either and in its default `composer.json` there is a requirement for **preserve-paths** which makes no observable profit. It seems to me that *we can safely remove this part* since we don't have it on Drupal 8's version and have no problems with that.

So yeah, the topic is about "let's add it to D8" while I say "no, let's remove it from D7 too" :)

I can create separate issue.

**Comment by derhasi** [comment]
@OnkelTem removing it from D7 will break most of the update procedures for most d7 sites. The main reason why _drupal-composer/preserve-paths_ exists, is that as soon as drupal/drupal is updated, the update would erase all files within the drupal installation root that are not part of the drupal/drupal itself. This means all your modules and themes in `sites/default/...` would be gone.

Conceptually _drupal-composer/preserve-paths_ allows "nested packages" to be preserved when the parent package is updated.
