### ISSUE TITLE
Adding an export/import configuration system

### ISSUE THREAD

**Issue by ghost** [drupal-composer/drupal-composer-project#303]
Hi !

I don't know if i'm in the right place to do this but i have a suggestion. (It's the first time i do this)
I wondered, could we include in the drupal-composer template this patch of drupal/core:
```
"drupal/core": {
     "[2788777] Allow a profile to be installed from existing config": "https://www.drupal.org/files/issues/2788777-91.patch"
  }
```

Next, create a config directory at root (defined in settings.php), then all you have to export go to this directory and any profile wich contains this line in *.info.yml will install the exported config:
```
config_install: true
```

Tell me if it's a bad/good idea and if drupal-composer/drupal-project would accept this kind of feature :)

**Comment by jcnventura** [comment]
Seems to be addressing a very specific need. This project should aim for the 99% drupal+composer projects. It also creates a maintenance nightmare. Note that in the ~1 month since this issue was created, the patch file is no longer 2788777-91.patch, and is now drupal-n2788777-105.patch.

The correct way to address this problem is in Drupal core, as that patch is currently doing.

**Comment by Chi-teck** [comment]
This seems outdated due
https://www.drupal.org/node/2897299

**Comment by normanlolx** [comment]
Isn't this issue outdated? https://www.drupal.org/node/2788777 got fixed and now is in core. Apart from that everybody is free to apply patches to their projects according their needs. This shouldn't be handled by this template.
