### ISSUE TITLE
Anyone using this with DrupalVM as a dependency?

### ISSUE THREAD

**Issue by paulcanning** [drupal-composer/drupal-composer-project#313]
If so, how is your setup configured?

I'm struggling to get my head around the whole `composer create-project` step for this project and the composer settings in DrupalVM.

**Comment by frob** [comment]
no problem, just create the project. Add the vagrant delegate file and add configuration as you need it.

Here are some links to doc pages:
http://docs.drupalvm.com/en/latest/deployment/composer/#using-composer-when-drupal-vm-is-a-composer-dependency-itself

http://docs.drupalvm.com/en/latest/deployment/composer-dependency/

**Comment by paulcanning** [comment]
I think it's the scaffolding files that threw me off. I didn't realise they only get created via the `create-project` command.

Drupal VM was running this command for me, so other devs using different local setups might not have had the additional files in the web directory.

Is there a list of what files should be tracked in the repo for team development?

I put the scaffold files in now so hopefully devs can use setups like Acquia Dev Desktop if they like.

**Comment by hawkeyetwolf** [comment]
The scaffold command is supposed to run anytime you `composer update`. If that isn't happening, then something else is awry. You can ask it run on `composer install` too by adding the command to the appropriate post-install hook, but I found that to be excessive and annoying because of the time it takes to download the scaffolding files.
