### ISSUE TITLE
Move drush/drush from a required dependency to a suggestion 

### ISSUE THREAD

**Issue by gnuget** [drupal-composer/drupal-composer-project#357]
I read  #352  and I agree that all the non-required dependencies should be moved to suggestions and drush is also part of those.

So, can we move it as well and let the user decide which project she wants to use?

**Comment by jackbravo** [comment]
I don't think they should be moved to suggested. Both drush and console are very useful as a starting point, which is what drupal-project gives: a useful starting point. I think without both of them, it becomes less useful. And since this is just a starting point, removing any of them I think is best left as an exercise to the user. Well, at least that is my opinion.

**Comment by FatherShawn** [comment]
After stating an opinion that we should should have both CLI in the same sections - I realize that I didn't state an opinion as to which.  I'm with @jackbravo - I use them on every drupal project and would leave them both in the project dependencies.  This project is for CLI management of a drupal project.

**Comment by pfrenssen** [comment]
As already discussed in the sister issue #352, we cannot move Drush to `suggest` because drupal-project depends on it, it is used in the test suite. Also I suggested to move Drush to `require-dev` in the PR (#353), but it was pointed out that Drush is currently installed on most production sites, and people expect it to be there. I agree with this, we should aim for the 80% use case.

So I think for the case of Drush the way forward is quite clear, it should remain in `require`. Drupal-console is still under discussion in #352.
