### ISSUE TITLE
Noob question on "root of drupal install"

### ISSUE THREAD

**Issue by femrich** [drupal-composer/drupal-composer-project#374]
I am a Composer beginner wrestling with understanding Composer in order to continue using Drupal (which I have used for many years). 

I am following the instructions at https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies and have set up a local install of drupal-composer/drupal-project on a Windows machine using Xampp. The filing system looks like this:

C:/xampp/htdocs/drupal8/web/

Now I want to use Composer to add some contrib modules.  The instructions at the drupal page listed above say:

To download contributed Drupal modules or themes with composer:

    Run composer require drupal/<modulename> 
    For example: composer require drupal/token
    This needs to be executed at the root of your Drupal install

My noob question:

In this situation, is the root of the Drupal install considered C:/xampp/htdocs/drupal8? (This folder contains composer.json and composer.lock) Or would root be considered (more likely, I think) C:/xampp/htdocs/drupal8/web? (This folder contains Drupal folders Core, Modules, Profiles, etc.)

And to execute the command to install a module, I first cd to the root folder, and then simply execute the command: Run composer require drupal/<modulename>, correct?

Thank you.

**Comment by fallenturtle** [comment]
I'm also noob to composer. I've been doing it from the root of the project (so drupal8, in your path above) and its working fine.

**Comment by femrich** [comment]
Thanks, @fallenturtle . Will try that. Nice to hear from another composer noob. I've spent a couple of weeks reading through documents with some trepidation. Have you made the leap to actually setting up a live drupal site with composer, or just working with localhost at this point? Any favorite support documents or sources you would recommend?

**Comment by FatherShawn** [comment]
The simplest answer is "in the directory where your `composer.json` is located. The mis-match between this project and that documentation page is that the Drupal tarball has the `composer.json` in the Drupal root directory because that's all it ships.  We put them, and the vendor directory, one level up.

**Comment by femrich** [comment]
Thank you, @FatherShawn . That helps!

**Comment by fallenturtle** [comment]
@femrich I have, but I'm not sure I did it right. That is, the site is working on production, but I might have installed a bunch of dev dependencies I didn't need to. That was using drupal/drupal and not this project. I can't find the guide right now (drupal.org seems to be having issues currently) but it was essentially push your site to a repo like bitbucket and then clone it to your production server and run compose install. This of course requires you to have CLI access to your server.
My server space provider requires the site associated with my main domain, which this drupal site will use, be located in public_html so I've already had to edit the package.json file for this project to use that instead of web.

**Comment by femrich** [comment]
@fallenturtle Thanks! I am about to attempt my first install of a live site with composer and none to sure I know how all the pieces fit together. Luckily my host service is flexible and helpful with advice, so we shall see. At times it feels like going from running a drupal site with basic installation to running a drupal site with composer installation is like going from being a home-schooled mechanic to being a home-schooled mechanic who creates all his own parts in a foundry. And much of the help material for composer assumes a level of knowledge I don't have yet. Seems like I can figure things out, but it's a long study with a steep learning curve.

**Comment by webflo** [comment]
@FatherShawn Thanks for your help!
