### ISSUE TITLE
composer error on "symfony/*" running documented update command

### ISSUE THREAD

**Issue by bradbulger** [drupal-composer/drupal-composer-project#416]
Related to #369 - if I run the documented command to update Drupal

`composer update drupal/core webflo/drupal-core-require-dev symfony/* --with-dependencies`

give me an error

`Package "symfony/*" listed for update is not installed. Ignoring.`

**Comment by MichelleCox** [comment]
I'm having the same issue.

**Comment by UltraBob** [comment]
Likewise.

**Comment by paul-m** [comment]
It's supposed to add all the Symfony dependencies, but unfortunately Composer can't do that. So I wrote them all out so you don't have to. Be sure and change your composer.json file to reflect the new core version you want (if needed).

`composer update drupal/core webflo/drupal-core-require-dev symfony/class-loader symfony/console symfony/dependency-injection symfony/event-dispatcher symfony/http-foundation symfony/http-kernel symfony/routing symfony/serializer symfony/translation symfony/validator symfony/process symfony/polyfill-iconv symfony/yaml symfony-cmf/routing symfony/psr-http-message-bridge --with-dependencies`

**Comment by logickal** [comment]
Does anyone know why this happens when it's explicitly called out in the composer update documentation as being a valid usage of the command?  It's the documented method of ensuring these symfony packages are updated, so I assume it works for some/most people, but obviously others of us are having to call all of these dependencies out explicitly.  I would love to figure out why.

**Comment by aronbeal** [comment]
I believe it's because the Symfony packages are dependencies of `drupal/core`, not directly included in the Drupal Project `composer.json`.  I can only surmise that the reason others are not getting this issue is because they have modified their `composer.json` to directly include certain Symfony packages.

In `[docroot]/core/composer.json` on a site after running `create-project`, you can see the Symfony dependencies directly.

I'm not sure why the `symfony/*` portion is required in the update command, if the `--with-dependencies` flag is supplied?  I wouldn't think it necessary.

**Comment by webflo** [comment]
> `I'm not sure why the symfony/* portion is required in the update command, if the --with-dependencies flag is supplied? I wouldn't think it necessary.`

@aronbeal It may be required if you have a certain symfony component in code base and Drupal did not require it until now. Drupal console has led a few times to this problem because it uses many symfony components.

**Comment by hansfn** [comment]
I have suggested to remove it - #524

**Comment by dzink** [comment]
I ran `composer self-update` which brought me from composer v1.6.4 to v1.9.1

After this, the asterisk worked.

**Comment by normanlolx** [comment]
Outdated.
