### ISSUE TITLE
D7: The requested PHP extension ext-pdo_mysql * is missing

### ISSUE THREAD

**Issue by hkirsman** [drupal-composer/drupal-composer-project#438]
The requested PHP extension ext-pdo_mysql * is missing from your system. Install or enable PHP's pdo_mysql extension.

I get this when executing:

    composer create-project drupal-composer/drupal-project:7.x-dev some-dir --stability dev --no-interaction

I don't need mysql as I first install the site and then initialize the project in Lando where everything exists. I think these requirements should not hinder getting the files. I haven't seen these kind of errors in D8 branch.

**Comment by normanlolx** [comment]
Have you tried it with `--ignore-platform-reqs`? As this flag is supposed to ignore `php`, `hhvm`, `lib-*` and `ext-*` requirements and force the installation even if the local machine does not fulfill these.

```bash
composer create-project drupal-composer/drupal-project:7.x-dev some-dir --stability dev --no-interaction --ignore-platform-reqs
```

**Comment by jcnventura** [comment]
You are right that it should not require mysql. Among others because you can also use pgsql.

I'll remove that requirement from the composer.json file.

For reference, drupal 8 core's composer.json also does not require any specific sql extension:
https://cgit.drupalcode.org/drupal/tree/core/composer.json
